const ShopActionTypes =
{
        COLLECTION_FETCH_START: "COLLECTION_FETCH_START",
        COLLECTION_FETCH_SUCCESS: "COLLECTION_FETCH_SUCCESS",
        COLLECTION_FETCH_FAILURE: "COLLECTION_FETCH_FAILURE",
}
export default ShopActionTypes;